spring:
  main:
    lazy-initialization: true
  # ==============================================================
  # = Data Source
  # ==============================================================
  datasource:
    url: "jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:typefrenzy}?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8"
    username: "${DB_USERNAME:typefrenzy}"
    password: "${DB_PASSWORD:password}"
    hikari:
      idle-timeout: 30000
      minimum-idle: "${MINIMUM_IDLE_CONNECTIONS_NUMBER: 5}"
      maximum-pool-size: "${CONNECTIONS_POOL_SIZE: 20}"
      max-lifetime: 60000
  # ==============================================================
  # = Hibernate ddl auto (create, create-drop, update) and the SQL dialect makes Hibernate generate better SQL for the chosen database
  # ==============================================================
  jpa:
    hibernate:
      ddl-auto: "${DB_DDL_AUTO:update}"
    properties:
      hibernate:
        dialect: "${DB_DIALECT:org.hibernate.dialect.MySQL8Dialect}"

management:
  endpoints:
    web:
      exposure:
        include: httptrace

frenzy:
  jwt:
    secret: "TypeFrenzy"
  paging:
    default-page-size: 10
  data:
    files-path: "${DATA_PATH:/opt/ourlovebooks-be/data/}"
